### PR TITLE
Update from JS to TS and remove unnecessary code

### PR DESCRIPTION
**Pull request by luizfilipezs**
This update allows the developer to decide which element to use as the toggler.

**Changes made**

- [x] Remove sample files
- [x] Initialize npm
- [x] Start using TypeScript
- [x] Update code according to ES2020
- [x] Remove default floating icon
- [x] Enable any element to be the toggler
- [x] Handle styles from JavaScript (with options)

With the new code, it is also possible to easily publish it on npm.

### CODE REVIEW

**Comment by anjalbinayak** [comment]
image
It's not working

**Comment by luizfilipezs** [comment]
Hi! You must install watchify and typescript globally:

npm i watchify -g

npm i typescript@latest -g

This solves the problem ;)

**Comment by anjalbinayak** [comment]
image
I installed and it stills shows this error

**Comment by luizfilipezs** [comment]
Ok! In the project folder, create another one called "js".

Inside "js", create other two files:

"index.js"
"dark-theme-switcher.js"

And try again ;)

**Comment by luizfilipezs** [comment]
Note that if it runs ok, all this command will do is create the js files
that you will be able to use in your browser.

But if you want to really make it run, inside the index.ts file you must
initialize the ThemeSwitcher as I mentioned in the README

**Comment by luizfilipezs** [comment]
Later, when this project becomes available on npm, users will be able to
import ThemeSwitcher to their projects and to use as they want, without the
need of run these commands or creating these folders

**Comment by anjalbinayak** [comment]
image
image 
the watchify and typescript issue is solved,
I am still not able to run it

**Comment by luizfilipezs** [comment]
In the HTML file, you must import the script "js/dark-theme-switcher.js".
And don't forget to add a button element with id="button" there =)

**Comment by luizfilipezs** [comment]
After it runs ok, remember to remove the code you added for tests. If you like the idea of my pull request, I can close this pull request and create a better one, with sample files that will avoid other developers to face the same issues you are facing now.

**Comment by anjalbinayak** [comment]
Yeah, your changes are awesome. I highly admire it.
Please create the new pull request with complete documentation and usage guide.
And Don't forget to include its main feature, the toggler should be draggable, and its  should show a context menu with toggler options like here https://binayak.codes/dark-theme-switcher/

At first, let's change the code into typescript and later we can make changes that will provide more value to this library

**Comment by luizfilipezs** [comment]
I'm glad you liked it! I'll be working on these features this week ;)

**Comment by anjalbinayak** [comment]
Looking forward to it :)

**Comment by luizfilipezs** [comment]
Hey, I did it! =)

Please, see [my forked repository](https://github.com/luizfilipezs/dark-theme-switcher), read the docs, and try it in your local machine. The project is already available on npm. So, I ask you to create an account there. Then I'll add you as a contributor to the package, with all privileges granted.

In order to keep working on the package, I ask you to add me as a contributor to _this_ repository. If you don't like this idea, I'll keep my forked repository being used in npm. Your name will be remembered: it will be there in README. The decision is totally yours. Thanks for your amazing contribution to open source.

**Comment by luizfilipezs** [comment]
I also remember that you've already added as a contributor to `package.json` file.

**Comment by luizfilipezs** [comment]
I'm only waiting for your response to make the pull request ;)

**Comment by anjalbinayak** [comment]
Make the pull request 🚀

**Comment by anjalbinayak** [comment]
https://www.npmjs.com/~anjalbinayak

**Pull request closed without merging**
